# Generated by Django 5.2.5 on 2025-08-30 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('expectancy', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('net_pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='finance_dashboard.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('entry', models.DecimalField(decimal_places=5, max_digits=10)),
                ('exit', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trade_type', models.CharField(choices=[('Live', 'Live'), ('Backtest', 'Backtest')], default='Live', max_length=8)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('ref', models.CharField(blank=True, max_length=20)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='finance_dashboard.portfolio')),
            ],
        ),
    ]
