# Generated by Django 5.2.5 on 2025-08-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0002_portfolioanalytics_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='buy_rate',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('Live', 'Live'), ('Backtest', 'Backtest')], max_length=10),
        ),
        migrations.DeleteModel(
            name='PortfolioAnalytics',
        ),
    ]
