# Generated by Django 5.2.5 on 2025-08-31 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0003_alter_portfolio_amount_alter_portfolio_buy_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='forex_pair',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='finance_dashboard.forexpair'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forexpair',
            name='current_rate',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trade',
            name='qty',
            field=models.IntegerField(default=10000),
        ),
    ]
