# Generated by Django 5.2.5 on 2025-08-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0004_portfolio_name_trade_forex_pair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='notes',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='ref',
            field=models.CharField(blank=True, default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='side',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('Live', 'Live'), ('Backtest', 'Backtest')], max_length=20),
        ),
    ]
