# Generated by Django 5.2.5 on 2025-08-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0005_alter_trade_notes_alter_trade_ref_alter_trade_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='stoploss',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
