# Generated by Django 5.2.5 on 2025-09-01 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0007_remove_portfolio_buy_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('result', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('analysis', models.TextField(blank=True)),
                ('lessons', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('portfolio_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_dashboard.portfolio')),
            ],
        ),
    ]
