# Generated by Django 5.2.5 on 2025-09-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0008_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
