# Generated by Django 5.2.5 on 2025-09-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0010_alter_insight_category_alter_insight_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
