# Generated by Django 5.2.5 on 2025-09-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0012_insight_author_insight_content_insight_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forexpair',
            options={'ordering': ['pair'], 'verbose_name_plural': 'Forex Pairs'},
        ),
        migrations.AlterModelOptions(
            name='insight',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Insights'},
        ),
        migrations.AlterModelOptions(
            name='macrodata',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Macro Data'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Trades'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='pair',
        ),
        migrations.AlterField(
            model_name='insight',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
