# Generated by Django 5.2.6 on 2025-09-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0013_alter_forexpair_options_alter_insight_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='entry_price',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='forex_pair',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='ref_insight',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='forex_pair',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('currency', 'Currency'), ('stock', 'Stock'), ('other', 'Other')], default='currency', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
