# Generated by Django 5.2.6 on 2025-10-02 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0014_remove_portfolio_entry_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macrodata',
            options={'ordering': ['date'], 'verbose_name_plural': 'Macro Data'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['date_added'], 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['date'], 'verbose_name_plural': 'Trades'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ref_insight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_references', to='finance_dashboard.insight'),
        ),
        migrations.AddField(
            model_name='trade',
            name='ref_insight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_references', to='finance_dashboard.insight'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='portfolio_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='finance_dashboard.portfolio'),
        ),
    ]
