# Generated by Django 5.2.6 on 2025-10-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0015_alter_macrodata_options_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='insight_attachments/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='insight',
            name='attached_image',
            field=models.ImageField(blank=True, null=True, upload_to='insight_images/%Y/%m/%d/'),
        ),
    ]
